### ISSUE TITLE
Deprecated homebrew option warning

### ISSUE THREAD

**Issue by bencalegari** [ericTsiliacos/portal#2]
👋🏻 hey eric, great tool you've got here. saw this when updating brew recently so i wanted to pass it along:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the erictsiliacos/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/erictsiliacos/homebrew-tap/portal.rb:7
```

**Comment by ericTsiliacos** [comment]
hey Ben! thanks for the heads up. I've made the fix in erictsiliacos/tap but it looks like on the client side you'll have to run `brew update` in order to see the fix. I'll mark this resolved.
